name: Docker Build, Test, and Deploy


on:
  push:
    branches: [main]
  pull:
    branches: [main]


jobs:

  test:

    runs_on: ubuntu-latest 

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build test image
      run: docker build -t mykoladmytrash/multi-test -f ./client/Dockerfile.dev ./client
    
    - name: Run test
      run: docker run -e CI=true mykoladmytrash/multi-test npm test


  deploy:

    runs_on: ubuntu-latest

    needs: test


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build production version
      run: |
        docker build -t client ./client
        docker build -t nginx ./nginx
        docker build -t server ./server
        docker build -t worker ./worker 

               