name: Docker Build, Test, and Deploy


on:
  push:
    branches: [main]


jobs:

  test:

    runs-on: ubuntu-latest 

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build test image
      run: docker build -t mykoladmytrash/multi-test -f ./client/Dockerfile.dev ./client
    
    - name: Run test
      run: docker run -e CI=true mykoladmytrash/multi-test npm test


  deploy:

    runs-on: ubuntu-latest

    needs: test


    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build production version and push to Docker Hub
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/client:latest ./client
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest ./nginx
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/server:latest ./server
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest ./worker 


        docker push ${{ secrets.DOCKERHUB_USERNAME }}/client:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/server:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest


               