name: Docker Build, Test, and Deploy


on:
  push:
    branches: [main]


jobs:

  test:

    runs_on: ubuntu-latest 

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build test image
      run: docker build -t mykoladmytrash/multi-test -f ./client/Dockerfile.dev ./client
    
    - name: Run test
      run: docker run -e CI=true mykoladmytrash/multi-test npm test


  deploy:

    runs_on: ubuntu-latest

    needs: test


    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{DOCKER_ID}}
        password: ${{DOCKER_TOKEN}}


    - name: Build production version and push to Docker Hub
      run: |
        docker build -t client ./client
        docker build -t nginx ./nginx
        docker build -t server ./server
        docker build -t worker ./worker 


        docker push client
        docker push nginx
        docker push server
        docker push worker


               